### ISSUE TITLE
The authencity of host can't be established

### ISSUE THREAD

**Issue by soinalastudio** [pyscripter/Ssh-Pascal#12]
Hello,
I trying to use your library and while connecting, I got this error: "The authencity of host ... can't be established. 
I tried using many programs like RemotedDB in android or HeidiSQL + Putty, there is no problem. Can you help me please?
Thank you for you libraries!
Regards

**Comment by pyscripter** [comment]
The host IP needs to be added to the knownhosts.

See  [TSshSession.CheckKnownHost](https://github.com/pyscripter/Ssh-Pascal/blob/master/Source/Ssh2Client.pas#L328)
and [TSshSession.ConfigKnownHostCheckPolicy](https://github.com/pyscripter/Ssh-Pascal/blob/master/Source/Ssh2Client.pas#L432C11-L432C23)

The default known_hosts file location is initialized as:

```pascal
  FKnownHostCheckSettings.KnownHostsFile := ExpandEnvStrings(
    IncludeTrailingPathDelimiter('%USERPROFILE%') + '.ssh\known_hosts');

```
You probably have not provided a keyboard callback using SetKeybInteractiveCallback.  Otherwise you would have been prompted to accept the host as known.
